<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Aletheia.Core\Aletheia.Core.csproj" />
    <ProjectReference Include="..\Aletheia.TimeSeries\Aletheia.TimeSeries.csproj" />
    <ProjectReference Include="..\Aletheia.Mathematics\Aletheia.Mathematics.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
