#nullable enable

using Aletheia.Desktop.Controls;

namespace Aletheia.Desktop;

partial class MainForm
{
    private System.ComponentModel.IContainer? components;
    private ToolTip toolTip = null!;
    private TableLayoutPanel rootLayout = null!;
    private Panel sidebar = null!;
    private TableLayoutPanel sidebarLayout = null!;
    private BrandMarkControl brandMark = null!;
    private FlowLayoutPanel navigation = null!;
    private Label portfolioSectionLabel = null!;
    private Label researchSectionLabel = null!;
    private Label modelsSectionLabel = null!;
    private Label systemSectionLabel = null!;
    private NavigationButton overviewNavigationButton = null!;
    private NavigationButton performanceNavigationButton = null!;
    private NavigationButton riskNavigationButton = null!;
    private NavigationButton simulationNavigationButton = null!;
    private NavigationButton dynamicsNavigationButton = null!;
    private NavigationButton spectralNavigationButton = null!;
    private NavigationButton analoguesNavigationButton = null!;
    private NavigationButton forecastNavigationButton = null!;
    private NavigationButton marketTimingNavigationButton = null!;
    private NavigationButton modelArenaNavigationButton = null!;
    private NavigationButton validationNavigationButton = null!;
    private NavigationButton predictionsNavigationButton = null!;
    private NavigationButton labNavigationButton = null!;
    private Panel sidebarFooterHost = null!;
    private SurfacePanel sidebarFooterCard = null!;
    private TableLayoutPanel sidebarFooterLayout = null!;
    private Label scientificModeLabel = null!;
    private Label scientificDescriptionLabel = null!;
    private TableLayoutPanel horizonSettingLayout = null!;
    private Label horizonSettingLabel = null!;
    private NumericUpDown horizonDaysInput = null!;
    private Label horizonDaysUnitLabel = null!;
    private Label versionSidebarLabel = null!;
    private Panel sidebarDivider = null!;
    private GradientPanel header = null!;
    private TableLayoutPanel headerLayout = null!;
    private TableLayoutPanel pageContext = null!;
    private Label pageTitleLabel = null!;
    private Label pageSubtitleLabel = null!;
    private Panel datasetHost = null!;
    private SurfacePanel datasetCard = null!;
    private TableLayoutPanel datasetLayout = null!;
    private Label datasetCaptionLabel = null!;
    private Label datasetNameLabel = null!;
    private Label datasetMetaLabel = null!;
    private Panel headerActionsHost = null!;
    private TableLayoutPanel headerActions = null!;
    private AletheiaButton changeFundButton = null!;
    private AletheiaButton loadSampleButton = null!;
    private AletheiaButton openCsvButton = null!;
    private AletheiaButton generateReportButton = null!;
    private Panel primaryActionSlot = null!;
    private AletheiaButton runArenaButton = null!;
    private AletheiaButton cancelButton = null!;
    private Panel headerDivider = null!;
    private Panel contentPanel = null!;
    private TableLayoutPanel statusLayout = null!;
    private StatusDotControl statusIndicator = null!;
    private Label statusLabel = null!;
    private ActivityBarControl operationProgress = null!;
    private Label versionStatusLabel = null!;

    private void InitializeComponent()
    {
        this.components = new System.ComponentModel.Container();
        this.toolTip = new ToolTip(this.components);
        this.rootLayout = new TableLayoutPanel();
        this.sidebar = new Panel();
        this.sidebarLayout = new TableLayoutPanel();
        this.brandMark = new BrandMarkControl();
        this.navigation = new FlowLayoutPanel();
        this.portfolioSectionLabel = new Label();
        this.researchSectionLabel = new Label();
        this.modelsSectionLabel = new Label();
        this.systemSectionLabel = new Label();
        this.overviewNavigationButton = new NavigationButton();
        this.performanceNavigationButton = new NavigationButton();
        this.riskNavigationButton = new NavigationButton();
        this.simulationNavigationButton = new NavigationButton();
        this.dynamicsNavigationButton = new NavigationButton();
        this.spectralNavigationButton = new NavigationButton();
        this.analoguesNavigationButton = new NavigationButton();
        this.forecastNavigationButton = new NavigationButton();
        this.marketTimingNavigationButton = new NavigationButton();
        this.modelArenaNavigationButton = new NavigationButton();
        this.validationNavigationButton = new NavigationButton();
        this.predictionsNavigationButton = new NavigationButton();
        this.labNavigationButton = new NavigationButton();
        this.sidebarFooterHost = new Panel();
        this.sidebarFooterCard = new SurfacePanel();
        this.sidebarFooterLayout = new TableLayoutPanel();
        this.scientificModeLabel = new Label();
        this.scientificDescriptionLabel = new Label();
        this.horizonSettingLayout = new TableLayoutPanel();
        this.horizonSettingLabel = new Label();
        this.horizonDaysInput = new NumericUpDown();
        this.horizonDaysUnitLabel = new Label();
        this.versionSidebarLabel = new Label();
        this.sidebarDivider = new Panel();
        this.header = new GradientPanel();
        this.headerLayout = new TableLayoutPanel();
        this.pageContext = new TableLayoutPanel();
        this.pageTitleLabel = new Label();
        this.pageSubtitleLabel = new Label();
        this.datasetHost = new Panel();
        this.datasetCard = new SurfacePanel();
        this.datasetLayout = new TableLayoutPanel();
        this.datasetCaptionLabel = new Label();
        this.datasetNameLabel = new Label();
        this.datasetMetaLabel = new Label();
        this.headerActionsHost = new Panel();
        this.headerActions = new TableLayoutPanel();
        this.changeFundButton = new AletheiaButton();
        this.loadSampleButton = new AletheiaButton();
        this.openCsvButton = new AletheiaButton();
        this.generateReportButton = new AletheiaButton();
        this.primaryActionSlot = new Panel();
        this.runArenaButton = new AletheiaButton();
        this.cancelButton = new AletheiaButton();
        this.headerDivider = new Panel();
        this.contentPanel = new Panel();
        this.statusLayout = new TableLayoutPanel();
        this.statusIndicator = new StatusDotControl();
        this.statusLabel = new Label();
        this.operationProgress = new ActivityBarControl();
        this.versionStatusLabel = new Label();
        this.rootLayout.SuspendLayout();
        this.sidebar.SuspendLayout();
        this.sidebarLayout.SuspendLayout();
        this.navigation.SuspendLayout();
        this.sidebarFooterHost.SuspendLayout();
        this.sidebarFooterCard.SuspendLayout();
        this.sidebarFooterLayout.SuspendLayout();
        this.horizonSettingLayout.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)this.horizonDaysInput).BeginInit();
        this.header.SuspendLayout();
        this.headerLayout.SuspendLayout();
        this.pageContext.SuspendLayout();
        this.datasetHost.SuspendLayout();
        this.datasetCard.SuspendLayout();
        this.datasetLayout.SuspendLayout();
        this.headerActionsHost.SuspendLayout();
        this.headerActions.SuspendLayout();
        this.primaryActionSlot.SuspendLayout();
        this.statusLayout.SuspendLayout();
        this.SuspendLayout();

        // rootLayout
        this.rootLayout.BackColor = Color.FromArgb(0, 7, 12);
        this.rootLayout.ColumnCount = 2;
        this.rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 280F));
        this.rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        this.rootLayout.Controls.Add(this.sidebar, 0, 0);
        this.rootLayout.Controls.Add(this.header, 1, 0);
        this.rootLayout.Controls.Add(this.contentPanel, 1, 1);
        this.rootLayout.Controls.Add(this.statusLayout, 1, 2);
        this.rootLayout.Dock = DockStyle.Fill;
        this.rootLayout.Margin = new Padding(0);
        this.rootLayout.Name = "ShellLayout";
        this.rootLayout.Padding = new Padding(0);
        this.rootLayout.RowCount = 3;
        this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 148F));
        this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
        this.rootLayout.SetRowSpan(this.sidebar, 3);

        // sidebar
        this.sidebar.BackColor = Color.FromArgb(0, 10, 18);
        this.sidebar.Controls.Add(this.sidebarLayout);
        this.sidebar.Controls.Add(this.sidebarDivider);
        this.sidebar.Dock = DockStyle.Fill;
        this.sidebar.Margin = new Padding(0);
        this.sidebar.Name = "sidebar";
        this.sidebar.Padding = new Padding(0);

        // sidebarLayout
        this.sidebarLayout.BackColor = Color.FromArgb(0, 10, 18);
        this.sidebarLayout.ColumnCount = 1;
        this.sidebarLayout.Controls.Add(this.brandMark, 0, 0);
        this.sidebarLayout.Controls.Add(this.navigation, 0, 1);
        this.sidebarLayout.Controls.Add(this.sidebarFooterHost, 0, 2);
        this.sidebarLayout.Dock = DockStyle.Fill;
        this.sidebarLayout.Margin = new Padding(0);
        this.sidebarLayout.Name = "sidebarLayout";
        this.sidebarLayout.Padding = new Padding(0);
        this.sidebarLayout.RowCount = 3;
        this.sidebarLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 126F));
        this.sidebarLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        this.sidebarLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 124F));

        // brandMark
        this.brandMark.Dock = DockStyle.Fill;
        this.brandMark.Name = "brandMark";

        // navigation
        this.navigation.AutoScroll = true;
        this.navigation.BackColor = Color.FromArgb(0, 10, 18);
        this.navigation.Controls.Add(this.portfolioSectionLabel);
        this.navigation.Controls.Add(this.overviewNavigationButton);
        this.navigation.Controls.Add(this.performanceNavigationButton);
        this.navigation.Controls.Add(this.riskNavigationButton);
        this.navigation.Controls.Add(this.simulationNavigationButton);
        this.navigation.Controls.Add(this.researchSectionLabel);
        this.navigation.Controls.Add(this.dynamicsNavigationButton);
        this.navigation.Controls.Add(this.spectralNavigationButton);
        this.navigation.Controls.Add(this.analoguesNavigationButton);
        this.navigation.Controls.Add(this.modelsSectionLabel);
        this.navigation.Controls.Add(this.forecastNavigationButton);
        this.navigation.Controls.Add(this.marketTimingNavigationButton);
        this.navigation.Controls.Add(this.modelArenaNavigationButton);
        this.navigation.Controls.Add(this.validationNavigationButton);
        this.navigation.Controls.Add(this.predictionsNavigationButton);
        this.navigation.Controls.Add(this.systemSectionLabel);
        this.navigation.Controls.Add(this.labNavigationButton);
        this.navigation.Dock = DockStyle.Fill;
        this.navigation.FlowDirection = FlowDirection.TopDown;
        this.navigation.Margin = new Padding(0);
        this.navigation.Name = "navigation";
        this.navigation.Padding = new Padding(4, 1, 4, 6);
        this.navigation.WrapContents = false;

        // section labels
        this.portfolioSectionLabel.Font = new Font("Consolas", 7.25F, FontStyle.Bold);
        this.portfolioSectionLabel.ForeColor = Color.FromArgb(129, 147, 157);
        this.portfolioSectionLabel.Height = 20;
        this.portfolioSectionLabel.Margin = new Padding(10, 2, 10, 1);
        this.portfolioSectionLabel.Name = "portfolioSectionLabel";
        this.portfolioSectionLabel.Text = "INVESTOR";
        this.portfolioSectionLabel.TextAlign = ContentAlignment.BottomLeft;
        this.portfolioSectionLabel.Width = 222;
        this.researchSectionLabel.Font = new Font("Consolas", 7.25F, FontStyle.Bold);
        this.researchSectionLabel.ForeColor = Color.FromArgb(129, 147, 157);
        this.researchSectionLabel.Height = 20;
        this.researchSectionLabel.Margin = new Padding(10, 8, 10, 1);
        this.researchSectionLabel.Name = "researchSectionLabel";
        this.researchSectionLabel.Text = "RESEARCH_STACK";
        this.researchSectionLabel.TextAlign = ContentAlignment.BottomLeft;
        this.researchSectionLabel.Width = 222;
        this.modelsSectionLabel.Font = new Font("Consolas", 7.25F, FontStyle.Bold);
        this.modelsSectionLabel.ForeColor = Color.FromArgb(129, 147, 157);
        this.modelsSectionLabel.Height = 20;
        this.modelsSectionLabel.Margin = new Padding(10, 8, 10, 1);
        this.modelsSectionLabel.Name = "modelsSectionLabel";
        this.modelsSectionLabel.Text = "PREDICTION";
        this.modelsSectionLabel.TextAlign = ContentAlignment.BottomLeft;
        this.modelsSectionLabel.Width = 222;
        this.systemSectionLabel.Font = new Font("Consolas", 7.25F, FontStyle.Bold);
        this.systemSectionLabel.ForeColor = Color.FromArgb(129, 147, 157);
        this.systemSectionLabel.Height = 20;
        this.systemSectionLabel.Margin = new Padding(10, 8, 10, 1);
        this.systemSectionLabel.Name = "systemSectionLabel";
        this.systemSectionLabel.Text = "SYSTEM";
        this.systemSectionLabel.TextAlign = ContentAlignment.BottomLeft;
        this.systemSectionLabel.Width = 222;

        // navigation buttons
        this.overviewNavigationButton.Monogram = "OV";
        this.overviewNavigationButton.Name = "overviewNavigationButton";
        this.overviewNavigationButton.Text = "Guidance";
        this.performanceNavigationButton.Monogram = "PF";
        this.performanceNavigationButton.Name = "performanceNavigationButton";
        this.performanceNavigationButton.Text = "Performance";
        this.riskNavigationButton.Monogram = "RK";
        this.riskNavigationButton.Name = "riskNavigationButton";
        this.riskNavigationButton.Text = "Risk";
        this.simulationNavigationButton.Monogram = "SI";
        this.simulationNavigationButton.Name = "simulationNavigationButton";
        this.simulationNavigationButton.Text = "Simulation";
        this.dynamicsNavigationButton.Monogram = "DY";
        this.dynamicsNavigationButton.Name = "dynamicsNavigationButton";
        this.dynamicsNavigationButton.Text = "Dynamics";
        this.spectralNavigationButton.Monogram = "SP";
        this.spectralNavigationButton.Name = "spectralNavigationButton";
        this.spectralNavigationButton.Text = "Spectral";
        this.analoguesNavigationButton.Monogram = "AN";
        this.analoguesNavigationButton.Name = "analoguesNavigationButton";
        this.analoguesNavigationButton.Text = "Analogues";
        this.forecastNavigationButton.Monogram = "FC";
        this.forecastNavigationButton.Name = "forecastNavigationButton";
        this.forecastNavigationButton.Text = "Forecasts";
        this.marketTimingNavigationButton.Monogram = "MT";
        this.marketTimingNavigationButton.Name = "marketTimingNavigationButton";
        this.marketTimingNavigationButton.Text = "Timing Guide";
        this.modelArenaNavigationButton.Monogram = "MA";
        this.modelArenaNavigationButton.Name = "modelArenaNavigationButton";
        this.modelArenaNavigationButton.Text = "Model Arena";
        this.validationNavigationButton.Monogram = "VA";
        this.validationNavigationButton.Name = "validationNavigationButton";
        this.validationNavigationButton.Text = "Validation";
        this.predictionsNavigationButton.Monogram = "PR";
        this.predictionsNavigationButton.Name = "predictionsNavigationButton";
        this.predictionsNavigationButton.Text = "Predictions";
        this.labNavigationButton.Monogram = "LB";
        this.labNavigationButton.Name = "labNavigationButton";
        this.labNavigationButton.Text = "Aletheia Lab";

        // sidebarFooterHost
        this.sidebarFooterHost.BackColor = Color.FromArgb(0, 10, 18);
        this.sidebarFooterHost.Controls.Add(this.sidebarFooterCard);
        this.sidebarFooterHost.Dock = DockStyle.Fill;
        this.sidebarFooterHost.Margin = new Padding(0);
        this.sidebarFooterHost.Name = "sidebarFooterHost";
        this.sidebarFooterHost.Padding = new Padding(12, 8, 12, 12);

        // sidebarFooterCard
        this.sidebarFooterCard.BorderColor = Color.FromArgb(26, 42, 52);
        this.sidebarFooterCard.Controls.Add(this.sidebarFooterLayout);
        this.sidebarFooterCard.CornerRadius = 8;
        this.sidebarFooterCard.Dock = DockStyle.Fill;
        this.sidebarFooterCard.FillColor = Color.FromArgb(0, 12, 22);
        this.sidebarFooterCard.Name = "sidebarFooterCard";
        this.sidebarFooterCard.Padding = new Padding(12, 9, 12, 8);

        // sidebarFooterLayout
        this.sidebarFooterLayout.BackColor = Color.FromArgb(0, 12, 22);
        this.sidebarFooterLayout.ColumnCount = 1;
        this.sidebarFooterLayout.Controls.Add(this.scientificModeLabel, 0, 0);
        this.sidebarFooterLayout.Controls.Add(this.scientificDescriptionLabel, 0, 1);
        this.sidebarFooterLayout.Controls.Add(this.horizonSettingLayout, 0, 2);
        this.sidebarFooterLayout.Controls.Add(this.versionSidebarLabel, 0, 3);
        this.sidebarFooterLayout.Dock = DockStyle.Fill;
        this.sidebarFooterLayout.Margin = new Padding(0);
        this.sidebarFooterLayout.Name = "sidebarFooterLayout";
        this.sidebarFooterLayout.RowCount = 4;
        this.sidebarFooterLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 18F));
        this.sidebarFooterLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        this.sidebarFooterLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        this.sidebarFooterLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 17F));
        this.scientificModeLabel.Dock = DockStyle.Fill;
        this.scientificModeLabel.Font = new Font("Consolas", 7.25F, FontStyle.Bold);
        this.scientificModeLabel.ForeColor = Color.FromArgb(96, 192, 224);
        this.scientificModeLabel.Name = "scientificModeLabel";
        this.scientificModeLabel.Text = "SYSTEM_READY";
        this.scientificModeLabel.TextAlign = ContentAlignment.MiddleLeft;
        this.scientificDescriptionLabel.Dock = DockStyle.Fill;
        this.scientificDescriptionLabel.Font = new Font("Segoe UI", 8F, FontStyle.Regular);
        this.scientificDescriptionLabel.ForeColor = Color.FromArgb(186, 200, 209);
        this.scientificDescriptionLabel.Name = "scientificDescriptionLabel";
        this.scientificDescriptionLabel.Text = "Investor guidance gated by evidence";
        this.scientificDescriptionLabel.TextAlign = ContentAlignment.MiddleLeft;

        // horizonSettingLayout
        this.horizonSettingLayout.BackColor = Color.FromArgb(0, 12, 22);
        this.horizonSettingLayout.ColumnCount = 3;
        this.horizonSettingLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        this.horizonSettingLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 58F));
        this.horizonSettingLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 46F));
        this.horizonSettingLayout.Controls.Add(this.horizonSettingLabel, 0, 0);
        this.horizonSettingLayout.Controls.Add(this.horizonDaysInput, 1, 0);
        this.horizonSettingLayout.Controls.Add(this.horizonDaysUnitLabel, 2, 0);
        this.horizonSettingLayout.Dock = DockStyle.Fill;
        this.horizonSettingLayout.Margin = new Padding(0);
        this.horizonSettingLayout.Name = "horizonSettingLayout";
        this.horizonSettingLayout.RowCount = 1;
        this.horizonSettingLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        this.horizonSettingLabel.AutoEllipsis = true;
        this.horizonSettingLabel.Dock = DockStyle.Fill;
        this.horizonSettingLabel.Font = new Font("Consolas", 7.25F, FontStyle.Bold);
        this.horizonSettingLabel.ForeColor = Color.FromArgb(129, 147, 157);
        this.horizonSettingLabel.Name = "horizonSettingLabel";
        this.horizonSettingLabel.Text = "VALIDATION_HORIZON";
        this.horizonSettingLabel.TextAlign = ContentAlignment.MiddleLeft;
        this.horizonDaysInput.BackColor = Color.FromArgb(0, 10, 18);
        this.horizonDaysInput.BorderStyle = BorderStyle.FixedSingle;
        this.horizonDaysInput.Dock = DockStyle.Fill;
        this.horizonDaysInput.Font = new Font("Consolas", 8F, FontStyle.Bold);
        this.horizonDaysInput.ForeColor = Color.FromArgb(238, 247, 251);
        this.horizonDaysInput.Increment = new decimal(new int[] { 30, 0, 0, 0 });
        this.horizonDaysInput.Margin = new Padding(2, 2, 4, 2);
        this.horizonDaysInput.Maximum = new decimal(new int[] { 730, 0, 0, 0 });
        this.horizonDaysInput.Minimum = new decimal(new int[] { 7, 0, 0, 0 });
        this.horizonDaysInput.Name = "ArenaHorizonDaysInput";
        this.horizonDaysInput.TextAlign = HorizontalAlignment.Right;
        this.horizonDaysInput.Value = new decimal(new int[] { 90, 0, 0, 0 });
        this.horizonDaysUnitLabel.Dock = DockStyle.Fill;
        this.horizonDaysUnitLabel.Font = new Font("Segoe UI", 7.75F, FontStyle.Regular);
        this.horizonDaysUnitLabel.ForeColor = Color.FromArgb(186, 200, 209);
        this.horizonDaysUnitLabel.Name = "horizonDaysUnitLabel";
        this.horizonDaysUnitLabel.Text = "days";
        this.horizonDaysUnitLabel.TextAlign = ContentAlignment.MiddleLeft;
        this.versionSidebarLabel.Dock = DockStyle.Fill;
        this.versionSidebarLabel.Font = new Font("Consolas", 7.25F, FontStyle.Bold);
        this.versionSidebarLabel.ForeColor = Color.FromArgb(128, 220, 255);
        this.versionSidebarLabel.Name = "versionSidebarLabel";
        this.versionSidebarLabel.Text = "v2.7.2";
        this.versionSidebarLabel.TextAlign = ContentAlignment.MiddleLeft;

        // sidebarDivider
        this.sidebarDivider.BackColor = Color.FromArgb(26, 42, 52);
        this.sidebarDivider.Dock = DockStyle.Right;
        this.sidebarDivider.Name = "sidebarDivider";
        this.sidebarDivider.Width = 1;

        // header
        this.header.BackColor = Color.FromArgb(0, 12, 22);
        this.header.Controls.Add(this.headerLayout);
        this.header.Controls.Add(this.headerDivider);
        this.header.Dock = DockStyle.Fill;
        this.header.Margin = new Padding(0);
        this.header.Name = "ShellHeader";
        this.header.Padding = new Padding(0);

        // headerLayout
        this.headerLayout.BackColor = Color.Transparent;
        this.headerLayout.ColumnCount = 3;
        this.headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 286F));
        this.headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        this.headerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 474F));
        this.headerLayout.Controls.Add(this.pageContext, 0, 0);
        this.headerLayout.Controls.Add(this.datasetHost, 1, 0);
        this.headerLayout.Controls.Add(this.headerActionsHost, 2, 0);
        this.headerLayout.Dock = DockStyle.Fill;
        this.headerLayout.Margin = new Padding(0);
        this.headerLayout.Name = "ShellHeaderLayout";
        this.headerLayout.Padding = new Padding(18, 14, 14, 13);
        this.headerLayout.RowCount = 1;
        this.headerLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));

        // pageContext
        this.pageContext.BackColor = Color.Transparent;
        this.pageContext.ColumnCount = 1;
        this.pageContext.Controls.Add(this.pageTitleLabel, 0, 1);
        this.pageContext.Controls.Add(this.pageSubtitleLabel, 0, 2);
        this.pageContext.Dock = DockStyle.Fill;
        this.pageContext.Margin = new Padding(0);
        this.pageContext.Name = "PageContext";
        this.pageContext.Padding = new Padding(0);
        this.pageContext.RowCount = 4;
        this.pageContext.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        this.pageContext.RowStyles.Add(new RowStyle(SizeType.Absolute, 46F));
        this.pageContext.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        this.pageContext.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        this.pageTitleLabel.AutoEllipsis = true;
        this.pageTitleLabel.AutoSize = false;
        this.pageTitleLabel.Dock = DockStyle.Fill;
        this.pageTitleLabel.Font = new Font("Consolas", 17F, FontStyle.Bold);
        this.pageTitleLabel.ForeColor = Color.FromArgb(255, 255, 255);
        this.pageTitleLabel.Margin = new Padding(0);
        this.pageTitleLabel.Name = "PageTitle";
        this.pageTitleLabel.Padding = new Padding(0);
        this.pageTitleLabel.Text = "Market Simulator";
        this.pageTitleLabel.TextAlign = ContentAlignment.MiddleLeft;
        this.pageTitleLabel.UseCompatibleTextRendering = false;
        this.pageSubtitleLabel.AutoEllipsis = true;
        this.pageSubtitleLabel.AutoSize = false;
        this.pageSubtitleLabel.Dock = DockStyle.Fill;
        this.pageSubtitleLabel.Font = new Font("Segoe UI", 8.5F, FontStyle.Regular);
        this.pageSubtitleLabel.ForeColor = Color.FromArgb(129, 147, 157);
        this.pageSubtitleLabel.Margin = new Padding(0);
        this.pageSubtitleLabel.Name = "PageSubtitle";
        this.pageSubtitleLabel.Padding = new Padding(0);
        this.pageSubtitleLabel.Text = "Search official funds, load CSV data and build investor guidance";
        this.pageSubtitleLabel.TextAlign = ContentAlignment.MiddleLeft;
        this.pageSubtitleLabel.UseCompatibleTextRendering = false;

        // datasetHost
        this.datasetHost.BackColor = Color.Transparent;
        this.datasetHost.Controls.Add(this.datasetCard);
        this.datasetHost.Dock = DockStyle.Fill;
        this.datasetHost.Margin = new Padding(0);
        this.datasetHost.Name = "datasetHost";
        this.datasetHost.Padding = new Padding(12, 3, 12, 3);

        // datasetCard
        this.datasetCard.BorderColor = Color.FromArgb(26, 42, 52);
        this.datasetCard.Controls.Add(this.datasetLayout);
        this.datasetCard.CornerRadius = 8;
        this.datasetCard.Dock = DockStyle.Fill;
        this.datasetCard.FillColor = Color.FromArgb(0, 10, 18);
        this.datasetCard.Name = "DatasetContextCard";
        this.datasetCard.Padding = new Padding(12, 10, 12, 10);

        // datasetLayout
        this.datasetLayout.BackColor = Color.FromArgb(0, 10, 18);
        this.datasetLayout.ColumnCount = 1;
        this.datasetLayout.Controls.Add(this.datasetCaptionLabel, 0, 1);
        this.datasetLayout.Controls.Add(this.datasetNameLabel, 0, 2);
        this.datasetLayout.Controls.Add(this.datasetMetaLabel, 0, 3);
        this.datasetLayout.Dock = DockStyle.Fill;
        this.datasetLayout.Margin = new Padding(0);
        this.datasetLayout.Name = "datasetLayout";
        this.datasetLayout.Padding = new Padding(0);
        this.datasetLayout.RowCount = 5;
        this.datasetLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        this.datasetLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 18F));
        this.datasetLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        this.datasetLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        this.datasetLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        this.datasetCaptionLabel.Dock = DockStyle.Fill;
        this.datasetCaptionLabel.Font = new Font("Consolas", 6.75F, FontStyle.Bold);
        this.datasetCaptionLabel.ForeColor = Color.FromArgb(96, 192, 224);
        this.datasetCaptionLabel.Margin = new Padding(0);
        this.datasetCaptionLabel.Name = "DatasetContextCaption";
        this.datasetCaptionLabel.Text = "ACTIVE DATASET";
        this.datasetCaptionLabel.TextAlign = ContentAlignment.MiddleLeft;
        this.datasetNameLabel.AutoEllipsis = true;
        this.datasetNameLabel.Dock = DockStyle.Fill;
        this.datasetNameLabel.Font = new Font("Consolas", 9F, FontStyle.Bold);
        this.datasetNameLabel.ForeColor = Color.FromArgb(238, 247, 251);
        this.datasetNameLabel.Margin = new Padding(0);
        this.datasetNameLabel.Name = "DatasetName";
        this.datasetNameLabel.Text = "No dataset selected";
        this.datasetNameLabel.TextAlign = ContentAlignment.MiddleLeft;
        this.datasetMetaLabel.AutoEllipsis = true;
        this.datasetMetaLabel.Dock = DockStyle.Fill;
        this.datasetMetaLabel.Font = new Font("Segoe UI", 7.75F, FontStyle.Regular);
        this.datasetMetaLabel.ForeColor = Color.FromArgb(129, 147, 157);
        this.datasetMetaLabel.Margin = new Padding(0);
        this.datasetMetaLabel.Name = "DatasetMetadata";
        this.datasetMetaLabel.Text = "Search CNMV or open a local CSV";
        this.datasetMetaLabel.TextAlign = ContentAlignment.MiddleLeft;

        // headerActionsHost
        this.headerActionsHost.BackColor = Color.Transparent;
        this.headerActionsHost.Controls.Add(this.headerActions);
        this.headerActionsHost.Dock = DockStyle.Fill;
        this.headerActionsHost.Margin = new Padding(0);
        this.headerActionsHost.Name = "HeaderActionsHost";
        this.headerActionsHost.Padding = new Padding(8, 40, 0, 40);

        // headerActions
        this.headerActions.BackColor = Color.Transparent;
        this.headerActions.ColumnCount = 5;
        this.headerActions.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 76F));
        this.headerActions.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 78F));
        this.headerActions.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 96F));
        this.headerActions.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 78F));
        this.headerActions.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        this.headerActions.Controls.Add(this.changeFundButton, 0, 0);
        this.headerActions.Controls.Add(this.loadSampleButton, 1, 0);
        this.headerActions.Controls.Add(this.openCsvButton, 2, 0);
        this.headerActions.Controls.Add(this.generateReportButton, 3, 0);
        this.headerActions.Controls.Add(this.primaryActionSlot, 4, 0);
        this.headerActions.Dock = DockStyle.Fill;
        this.headerActions.Margin = new Padding(0);
        this.headerActions.Name = "HeaderActions";
        this.headerActions.Padding = new Padding(0);
        this.headerActions.RowCount = 1;
        this.headerActions.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));

        // changeFundButton
        this.changeFundButton.AccessibleName = "Funds";
        this.changeFundButton.AccessibleRole = AccessibleRole.PushButton;
        this.changeFundButton.BackColor = Color.FromArgb(13, 32, 44);
        this.changeFundButton.Cursor = Cursors.Hand;
        this.changeFundButton.Dock = DockStyle.Fill;
        this.changeFundButton.Kind = AletheiaButtonKind.Secondary;
        this.changeFundButton.FlatAppearance.BorderColor = Color.FromArgb(38, 57, 70);
        this.changeFundButton.FlatAppearance.BorderSize = 1;
        this.changeFundButton.FlatAppearance.MouseDownBackColor = Color.FromArgb(20, 56, 74);
        this.changeFundButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(13, 32, 44);
        this.changeFundButton.FlatStyle = FlatStyle.Flat;
        this.changeFundButton.Font = new Font("Consolas", 8.5F, FontStyle.Bold);
        this.changeFundButton.ForeColor = Color.FromArgb(238, 247, 251);
        this.changeFundButton.Margin = new Padding(0, 0, 4, 0);
        this.changeFundButton.Name = "ChangeFundButton";
        this.changeFundButton.TabStop = true;
        this.changeFundButton.Text = "FUNDS";
        this.changeFundButton.UseVisualStyleBackColor = false;

        // loadSampleButton
        this.loadSampleButton.AccessibleName = "Sample";
        this.loadSampleButton.AccessibleRole = AccessibleRole.PushButton;
        this.loadSampleButton.BackColor = Color.FromArgb(13, 32, 44);
        this.loadSampleButton.Cursor = Cursors.Hand;
        this.loadSampleButton.Dock = DockStyle.Fill;
        this.loadSampleButton.Kind = AletheiaButtonKind.Secondary;
        this.loadSampleButton.FlatAppearance.BorderColor = Color.FromArgb(38, 57, 70);
        this.loadSampleButton.FlatAppearance.BorderSize = 1;
        this.loadSampleButton.FlatAppearance.MouseDownBackColor = Color.FromArgb(20, 56, 74);
        this.loadSampleButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(13, 32, 44);
        this.loadSampleButton.FlatStyle = FlatStyle.Flat;
        this.loadSampleButton.Font = new Font("Consolas", 8.5F, FontStyle.Bold);
        this.loadSampleButton.ForeColor = Color.FromArgb(238, 247, 251);
        this.loadSampleButton.Margin = new Padding(4, 0, 4, 0);
        this.loadSampleButton.Name = "LoadSampleButton";
        this.loadSampleButton.TabStop = true;
        this.loadSampleButton.Text = "SAMPLE";
        this.loadSampleButton.UseVisualStyleBackColor = false;

        // openCsvButton
        this.openCsvButton.AccessibleName = "Open CSV";
        this.openCsvButton.AccessibleRole = AccessibleRole.PushButton;
        this.openCsvButton.BackColor = Color.FromArgb(13, 32, 44);
        this.openCsvButton.Cursor = Cursors.Hand;
        this.openCsvButton.Dock = DockStyle.Fill;
        this.openCsvButton.Kind = AletheiaButtonKind.Secondary;
        this.openCsvButton.FlatAppearance.BorderColor = Color.FromArgb(38, 57, 70);
        this.openCsvButton.FlatAppearance.BorderSize = 1;
        this.openCsvButton.FlatAppearance.MouseDownBackColor = Color.FromArgb(20, 56, 74);
        this.openCsvButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(13, 32, 44);
        this.openCsvButton.FlatStyle = FlatStyle.Flat;
        this.openCsvButton.Font = new Font("Consolas", 8.5F, FontStyle.Bold);
        this.openCsvButton.ForeColor = Color.FromArgb(238, 247, 251);
        this.openCsvButton.Margin = new Padding(4, 0, 4, 0);
        this.openCsvButton.Name = "OpenCsvButton";
        this.openCsvButton.TabStop = true;
        this.openCsvButton.Text = "OPEN CSV";
        this.openCsvButton.UseVisualStyleBackColor = false;

        // generateReportButton
        this.generateReportButton.AccessibleName = "Generate report";
        this.generateReportButton.AccessibleRole = AccessibleRole.PushButton;
        this.generateReportButton.BackColor = Color.FromArgb(13, 32, 44);
        this.generateReportButton.Cursor = Cursors.Hand;
        this.generateReportButton.Dock = DockStyle.Fill;
        this.generateReportButton.Kind = AletheiaButtonKind.Secondary;
        this.generateReportButton.FlatAppearance.BorderColor = Color.FromArgb(38, 57, 70);
        this.generateReportButton.FlatAppearance.BorderSize = 1;
        this.generateReportButton.FlatAppearance.MouseDownBackColor = Color.FromArgb(20, 56, 74);
        this.generateReportButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(13, 32, 44);
        this.generateReportButton.FlatStyle = FlatStyle.Flat;
        this.generateReportButton.Font = new Font("Consolas", 8.5F, FontStyle.Bold);
        this.generateReportButton.ForeColor = Color.FromArgb(238, 247, 251);
        this.generateReportButton.Margin = new Padding(4, 0, 4, 0);
        this.generateReportButton.Name = "GenerateReportButton";
        this.generateReportButton.TabStop = true;
        this.generateReportButton.Text = "REPORT";
        this.generateReportButton.UseVisualStyleBackColor = false;

        // primaryActionSlot
        this.primaryActionSlot.BackColor = Color.Transparent;
        this.primaryActionSlot.Controls.Add(this.runArenaButton);
        this.primaryActionSlot.Controls.Add(this.cancelButton);
        this.primaryActionSlot.Dock = DockStyle.Fill;
        this.primaryActionSlot.Margin = new Padding(0);
        this.primaryActionSlot.Name = "primaryActionSlot";
        this.primaryActionSlot.Padding = new Padding(0);

        // runArenaButton
        this.runArenaButton.AccessibleName = "Run Model Arena for 90 calendar days";
        this.runArenaButton.AccessibleRole = AccessibleRole.PushButton;
        this.runArenaButton.BackColor = Color.FromArgb(96, 192, 224);
        this.runArenaButton.Cursor = Cursors.Hand;
        this.runArenaButton.Dock = DockStyle.Fill;
        this.runArenaButton.Kind = AletheiaButtonKind.Primary;
        this.runArenaButton.FlatAppearance.BorderColor = Color.FromArgb(96, 192, 224);
        this.runArenaButton.FlatAppearance.BorderSize = 1;
        this.runArenaButton.FlatAppearance.MouseDownBackColor = Color.FromArgb(128, 220, 255);
        this.runArenaButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(105, 205, 235);
        this.runArenaButton.FlatStyle = FlatStyle.Flat;
        this.runArenaButton.Font = new Font("Consolas", 8.5F, FontStyle.Bold);
        this.runArenaButton.ForeColor = Color.FromArgb(0, 7, 12);
        this.runArenaButton.Margin = new Padding(4, 0, 0, 0);
        this.runArenaButton.Name = "RunArenaButton";
        this.runArenaButton.TabStop = true;
        this.runArenaButton.Text = "RUN 90D";
        this.runArenaButton.UseVisualStyleBackColor = false;

        // cancelButton
        this.cancelButton.AccessibleName = "Cancel";
        this.cancelButton.AccessibleRole = AccessibleRole.PushButton;
        this.cancelButton.BackColor = Color.FromArgb(53, 18, 28);
        this.cancelButton.Cursor = Cursors.Hand;
        this.cancelButton.Dock = DockStyle.Fill;
        this.cancelButton.Kind = AletheiaButtonKind.Danger;
        this.cancelButton.FlatAppearance.BorderColor = Color.FromArgb(255, 94, 122);
        this.cancelButton.FlatAppearance.BorderSize = 1;
        this.cancelButton.FlatAppearance.MouseDownBackColor = Color.FromArgb(63, 31, 42);
        this.cancelButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(53, 18, 28);
        this.cancelButton.FlatStyle = FlatStyle.Flat;
        this.cancelButton.Font = new Font("Consolas", 8.5F, FontStyle.Bold);
        this.cancelButton.ForeColor = Color.FromArgb(255, 94, 122);
        this.cancelButton.Margin = new Padding(4, 0, 0, 0);
        this.cancelButton.Name = "CancelButton";
        this.cancelButton.TabStop = true;
        this.cancelButton.Text = "CANCEL";
        this.cancelButton.UseVisualStyleBackColor = false;
        this.cancelButton.Visible = false;

        // headerDivider
        this.headerDivider.BackColor = Color.FromArgb(26, 42, 52);
        this.headerDivider.Dock = DockStyle.Bottom;
        this.headerDivider.Height = 1;
        this.headerDivider.Name = "headerDivider";

        // contentPanel
        this.contentPanel.BackColor = Color.FromArgb(0, 7, 12);
        this.contentPanel.Dock = DockStyle.Fill;
        this.contentPanel.Margin = new Padding(0);
        this.contentPanel.Name = "ContentPanel";
        this.contentPanel.Padding = new Padding(10, 8, 10, 10);

        // statusLayout
        this.statusLayout.BackColor = Color.FromArgb(0, 12, 22);
        this.statusLayout.ColumnCount = 4;
        this.statusLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 18F));
        this.statusLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        this.statusLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 180F));
        this.statusLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 240F));
        this.statusLayout.Controls.Add(this.statusIndicator, 0, 0);
        this.statusLayout.Controls.Add(this.statusLabel, 1, 0);
        this.statusLayout.Controls.Add(this.operationProgress, 2, 0);
        this.statusLayout.Controls.Add(this.versionStatusLabel, 3, 0);
        this.statusLayout.Dock = DockStyle.Fill;
        this.statusLayout.Margin = new Padding(0);
        this.statusLayout.Name = "statusLayout";
        this.statusLayout.Padding = new Padding(10, 5, 12, 4);
        this.statusLayout.RowCount = 1;
        this.statusLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        this.statusIndicator.Dock = DockStyle.Fill;
        this.statusIndicator.Name = "statusIndicator";
        this.statusLabel.AutoEllipsis = true;
        this.statusLabel.Dock = DockStyle.Fill;
        this.statusLabel.Font = new Font("Segoe UI", 8F, FontStyle.Regular);
        this.statusLabel.ForeColor = Color.FromArgb(186, 200, 209);
        this.statusLabel.Name = "statusLabel";
        this.statusLabel.Text = "Ready";
        this.statusLabel.TextAlign = ContentAlignment.MiddleLeft;
        this.operationProgress.Dock = DockStyle.Fill;
        this.operationProgress.Margin = new Padding(10, 8, 10, 7);
        this.operationProgress.Name = "operationProgress";
        this.operationProgress.Visible = false;
        this.versionStatusLabel.Dock = DockStyle.Fill;
        this.versionStatusLabel.Font = new Font("Segoe UI", 7.25F, FontStyle.Regular);
        this.versionStatusLabel.ForeColor = Color.FromArgb(129, 147, 157);
        this.versionStatusLabel.Name = "versionStatusLabel";
        this.versionStatusLabel.Text = "Aletheia 2.7.2 · EIDO MARKET LAB";
        this.versionStatusLabel.TextAlign = ContentAlignment.MiddleRight;

        // MainForm
        this.AutoScaleDimensions = new SizeF(96F, 96F);
        this.AutoScaleMode = AutoScaleMode.Dpi;
        this.BackColor = Color.FromArgb(0, 7, 12);
        this.ClientSize = new Size(1460, 900);
        this.Controls.Add(this.rootLayout);
        this.DoubleBuffered = true;
        this.Font = new Font("Segoe UI", 9F, FontStyle.Regular);
        this.ForeColor = Color.FromArgb(238, 247, 251);
        this.KeyPreview = true;
        this.MinimumSize = new Size(1180, 720);
        this.Name = "MainForm";
        this.StartPosition = FormStartPosition.CenterScreen;
        this.Text = "Aletheia 2.7.2 - EIDO Market Simulator";
        this.statusLayout.ResumeLayout(false);
        this.primaryActionSlot.ResumeLayout(false);
        this.headerActions.ResumeLayout(false);
        this.headerActionsHost.ResumeLayout(false);
        this.datasetLayout.ResumeLayout(false);
        this.datasetCard.ResumeLayout(false);
        this.datasetHost.ResumeLayout(false);
        this.pageContext.ResumeLayout(false);
        this.headerLayout.ResumeLayout(false);
        this.header.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)this.horizonDaysInput).EndInit();
        this.horizonSettingLayout.ResumeLayout(false);
        this.sidebarFooterLayout.ResumeLayout(false);
        this.sidebarFooterCard.ResumeLayout(false);
        this.sidebarFooterHost.ResumeLayout(false);
        this.navigation.ResumeLayout(false);
        this.sidebarLayout.ResumeLayout(false);
        this.sidebar.ResumeLayout(false);
        this.rootLayout.ResumeLayout(false);
        this.ResumeLayout(false);
    }
}
