using Aletheia.Desktop.Controls;

namespace Aletheia.Desktop.Pages;

partial class SimulationPage
{
    private TableLayoutPanel rootLayout = null!;
    private SurfacePanel configurationCard = null!;
    private TableLayoutPanel configurationLayout = null!;
    private TableLayoutPanel configurationHeader = null!;
    private Label configurationTitleLabel = null!;
    private Label configurationDescriptionLabel = null!;
    private SurfacePanel datasetCard = null!;
    private TableLayoutPanel datasetLayout = null!;
    private Label datasetIconLabel = null!;
    private Label fundNameLabel = null!;
    private Label fundMetaLabel = null!;
    private Label planParametersLabel = null!;
    private TableLayoutPanel initialCapitalRow = null!;
    private TableLayoutPanel initialCapitalCopy = null!;
    private Label initialCapitalTitle = null!;
    private Label initialCapitalDescription = null!;
    private SurfacePanel initialCapitalFrame = null!;
    private NumericUpDown initialInvestment = null!;
    private TableLayoutPanel monthlyContributionRow = null!;
    private TableLayoutPanel monthlyContributionCopy = null!;
    private Label monthlyContributionTitle = null!;
    private Label monthlyContributionDescription = null!;
    private SurfacePanel monthlyContributionFrame = null!;
    private NumericUpDown monthlyContribution = null!;
    private TableLayoutPanel horizonYearsRow = null!;
    private TableLayoutPanel horizonYearsCopy = null!;
    private Label horizonYearsTitle = null!;
    private Label horizonYearsDescription = null!;
    private SurfacePanel horizonYearsFrame = null!;
    private NumericUpDown horizonYears = null!;
    private TableLayoutPanel pathCountRow = null!;
    private TableLayoutPanel pathCountCopy = null!;
    private Label pathCountTitle = null!;
    private Label pathCountDescription = null!;
    private SurfacePanel pathCountFrame = null!;
    private NumericUpDown pathCount = null!;
    private AletheiaButton runButton = null!;
    private SurfacePanel assumptionCard = null!;
    private TableLayoutPanel assumptionLayout = null!;
    private Label assumptionTitleLabel = null!;
    private Label assumptionDescriptionLabel = null!;
    private Label stateLabel = null!;
    private TableLayoutPanel resultsLayout = null!;
    private MetricStripControl metrics = null!;
    private TimeSeriesChartControl trajectoryChart = null!;
    private DataGridCardControl detailsCard = null!;

    private void InitializeComponent()
    {
        this.rootLayout = new TableLayoutPanel();
        this.configurationCard = new SurfacePanel();
        this.configurationLayout = new TableLayoutPanel();
        this.configurationHeader = new TableLayoutPanel();
        this.configurationTitleLabel = new Label();
        this.configurationDescriptionLabel = new Label();
        this.datasetCard = new SurfacePanel();
        this.datasetLayout = new TableLayoutPanel();
        this.datasetIconLabel = new Label();
        this.fundNameLabel = new Label();
        this.fundMetaLabel = new Label();
        this.planParametersLabel = new Label();
        this.initialCapitalRow = new TableLayoutPanel();
        this.initialCapitalCopy = new TableLayoutPanel();
        this.initialCapitalTitle = new Label();
        this.initialCapitalDescription = new Label();
        this.initialCapitalFrame = new SurfacePanel();
        this.initialInvestment = new NumericUpDown();
        this.monthlyContributionRow = new TableLayoutPanel();
        this.monthlyContributionCopy = new TableLayoutPanel();
        this.monthlyContributionTitle = new Label();
        this.monthlyContributionDescription = new Label();
        this.monthlyContributionFrame = new SurfacePanel();
        this.monthlyContribution = new NumericUpDown();
        this.horizonYearsRow = new TableLayoutPanel();
        this.horizonYearsCopy = new TableLayoutPanel();
        this.horizonYearsTitle = new Label();
        this.horizonYearsDescription = new Label();
        this.horizonYearsFrame = new SurfacePanel();
        this.horizonYears = new NumericUpDown();
        this.pathCountRow = new TableLayoutPanel();
        this.pathCountCopy = new TableLayoutPanel();
        this.pathCountTitle = new Label();
        this.pathCountDescription = new Label();
        this.pathCountFrame = new SurfacePanel();
        this.pathCount = new NumericUpDown();
        this.runButton = new AletheiaButton();
        this.assumptionCard = new SurfacePanel();
        this.assumptionLayout = new TableLayoutPanel();
        this.assumptionTitleLabel = new Label();
        this.assumptionDescriptionLabel = new Label();
        this.stateLabel = new Label();
        this.resultsLayout = new TableLayoutPanel();
        this.metrics = new MetricStripControl();
        this.trajectoryChart = new TimeSeriesChartControl();
        this.detailsCard = new DataGridCardControl();
        ((System.ComponentModel.ISupportInitialize)this.initialInvestment).BeginInit();
        ((System.ComponentModel.ISupportInitialize)this.monthlyContribution).BeginInit();
        ((System.ComponentModel.ISupportInitialize)this.horizonYears).BeginInit();
        ((System.ComponentModel.ISupportInitialize)this.pathCount).BeginInit();
        this.rootLayout.SuspendLayout();
        this.configurationCard.SuspendLayout();
        this.configurationLayout.SuspendLayout();
        this.configurationHeader.SuspendLayout();
        this.datasetCard.SuspendLayout();
        this.datasetLayout.SuspendLayout();
        this.initialCapitalRow.SuspendLayout();
        this.initialCapitalCopy.SuspendLayout();
        this.initialCapitalTitle.SuspendLayout();
        this.initialCapitalDescription.SuspendLayout();
        this.initialCapitalFrame.SuspendLayout();
        this.monthlyContributionRow.SuspendLayout();
        this.monthlyContributionCopy.SuspendLayout();
        this.monthlyContributionTitle.SuspendLayout();
        this.monthlyContributionDescription.SuspendLayout();
        this.monthlyContributionFrame.SuspendLayout();
        this.horizonYearsRow.SuspendLayout();
        this.horizonYearsCopy.SuspendLayout();
        this.horizonYearsTitle.SuspendLayout();
        this.horizonYearsDescription.SuspendLayout();
        this.horizonYearsFrame.SuspendLayout();
        this.pathCountRow.SuspendLayout();
        this.pathCountCopy.SuspendLayout();
        this.pathCountTitle.SuspendLayout();
        this.pathCountDescription.SuspendLayout();
        this.pathCountFrame.SuspendLayout();
        this.assumptionCard.SuspendLayout();
        this.assumptionLayout.SuspendLayout();
        this.resultsLayout.SuspendLayout();
        this.SuspendLayout();

        // rootLayout
        this.rootLayout.BackColor = Color.FromArgb(0, 7, 12);
        this.rootLayout.ColumnCount = 2;
        this.rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 372F));
        this.rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        this.rootLayout.Controls.Add(this.configurationCard, 0, 0);
        this.rootLayout.Controls.Add(this.resultsLayout, 1, 0);
        this.rootLayout.Dock = DockStyle.Fill;
        this.rootLayout.Margin = new Padding(0);
        this.rootLayout.Name = "rootLayout";
        this.rootLayout.Padding = new Padding(0);
        this.rootLayout.RowCount = 1;
        this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));

        // configurationCard
        this.configurationCard.BorderColor = Color.FromArgb(26, 42, 52);
        this.configurationCard.Controls.Add(this.configurationLayout);
        this.configurationCard.CornerRadius = 8;
        this.configurationCard.Dock = DockStyle.Fill;
        this.configurationCard.FillColor = Color.FromArgb(0, 10, 18);
        this.configurationCard.Margin = new Padding(6);
        this.configurationCard.Name = "configurationCard";
        this.configurationCard.Padding = new Padding(1);

        // configurationLayout
        this.configurationLayout.BackColor = Color.FromArgb(0, 10, 18);
        this.configurationLayout.ColumnCount = 1;
        this.configurationLayout.Controls.Add(this.configurationHeader, 0, 0);
        this.configurationLayout.Controls.Add(this.datasetCard, 0, 1);
        this.configurationLayout.Controls.Add(this.planParametersLabel, 0, 2);
        this.configurationLayout.Controls.Add(this.initialCapitalRow, 0, 3);
        this.configurationLayout.Controls.Add(this.monthlyContributionRow, 0, 4);
        this.configurationLayout.Controls.Add(this.horizonYearsRow, 0, 5);
        this.configurationLayout.Controls.Add(this.pathCountRow, 0, 6);
        this.configurationLayout.Controls.Add(this.runButton, 0, 7);
        this.configurationLayout.Controls.Add(this.assumptionCard, 0, 8);
        this.configurationLayout.Controls.Add(this.stateLabel, 0, 9);
        this.configurationLayout.Dock = DockStyle.Fill;
        this.configurationLayout.Margin = new Padding(0);
        this.configurationLayout.Name = "configurationLayout";
        this.configurationLayout.Padding = new Padding(15, 12, 15, 12);
        this.configurationLayout.RowCount = 10;
        this.configurationLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 52F));
        this.configurationLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 60F));
        this.configurationLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
        this.configurationLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        this.configurationLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        this.configurationLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        this.configurationLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        this.configurationLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        this.configurationLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 82F));
        this.configurationLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));

        // configurationHeader
        this.configurationHeader.BackColor = Color.FromArgb(0, 10, 18);
        this.configurationHeader.ColumnCount = 1;
        this.configurationHeader.Controls.Add(this.configurationTitleLabel, 0, 0);
        this.configurationHeader.Controls.Add(this.configurationDescriptionLabel, 0, 1);
        this.configurationHeader.Dock = DockStyle.Fill;
        this.configurationHeader.Margin = new Padding(0);
        this.configurationHeader.Name = "configurationHeader";
        this.configurationHeader.RowCount = 2;
        this.configurationHeader.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        this.configurationHeader.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        this.configurationTitleLabel.Dock = DockStyle.Fill;
        this.configurationTitleLabel.Font = new Font("Consolas", 15F, FontStyle.Bold);
        this.configurationTitleLabel.ForeColor = Color.FromArgb(255, 255, 255);
        this.configurationTitleLabel.Name = "configurationTitleLabel";
        this.configurationTitleLabel.Text = "Investment scenario";
        this.configurationTitleLabel.TextAlign = ContentAlignment.MiddleLeft;
        this.configurationDescriptionLabel.AutoEllipsis = true;
        this.configurationDescriptionLabel.Dock = DockStyle.Fill;
        this.configurationDescriptionLabel.Font = new Font("Segoe UI", 8.5F, FontStyle.Regular);
        this.configurationDescriptionLabel.ForeColor = Color.FromArgb(186, 200, 209);
        this.configurationDescriptionLabel.Name = "configurationDescriptionLabel";
        this.configurationDescriptionLabel.Text = "Stress-test a periodic contribution plan against the historical return distribution.";
        this.configurationDescriptionLabel.TextAlign = ContentAlignment.TopLeft;

        // datasetCard
        this.datasetCard.BorderColor = Color.FromArgb(26, 42, 52);
        this.datasetCard.Controls.Add(this.datasetLayout);
        this.datasetCard.CornerRadius = 8;
        this.datasetCard.Dock = DockStyle.Fill;
        this.datasetCard.FillColor = Color.FromArgb(0, 12, 22);
        this.datasetCard.Margin = new Padding(0, 5, 0, 7);
        this.datasetCard.Name = "datasetCard";
        this.datasetCard.Padding = new Padding(12, 8, 12, 7);
        this.datasetLayout.BackColor = Color.FromArgb(0, 12, 22);
        this.datasetLayout.ColumnCount = 2;
        this.datasetLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 44F));
        this.datasetLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        this.datasetLayout.Controls.Add(this.datasetIconLabel, 0, 0);
        this.datasetLayout.Controls.Add(this.fundNameLabel, 1, 0);
        this.datasetLayout.Controls.Add(this.fundMetaLabel, 1, 1);
        this.datasetLayout.Dock = DockStyle.Fill;
        this.datasetLayout.Margin = new Padding(0);
        this.datasetLayout.Name = "datasetLayout";
        this.datasetLayout.RowCount = 2;
        this.datasetLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 55F));
        this.datasetLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 45F));
        this.datasetLayout.SetRowSpan(this.datasetIconLabel, 2);
        this.datasetIconLabel.Dock = DockStyle.Fill;
        this.datasetIconLabel.Font = new Font("Consolas", 17F, FontStyle.Bold);
        this.datasetIconLabel.ForeColor = Color.FromArgb(96, 192, 224);
        this.datasetIconLabel.Name = "datasetIconLabel";
        this.datasetIconLabel.Text = "Σ";
        this.datasetIconLabel.TextAlign = ContentAlignment.MiddleCenter;
        this.fundNameLabel.AutoEllipsis = true;
        this.fundNameLabel.Dock = DockStyle.Fill;
        this.fundNameLabel.Font = new Font("Consolas", 9F, FontStyle.Bold);
        this.fundNameLabel.ForeColor = Color.FromArgb(255, 255, 255);
        this.fundNameLabel.Name = "fundNameLabel";
        this.fundNameLabel.Text = "No active dataset";
        this.fundNameLabel.TextAlign = ContentAlignment.BottomLeft;
        this.fundMetaLabel.AutoEllipsis = true;
        this.fundMetaLabel.Dock = DockStyle.Fill;
        this.fundMetaLabel.Font = new Font("Segoe UI", 7.75F, FontStyle.Regular);
        this.fundMetaLabel.ForeColor = Color.FromArgb(129, 147, 157);
        this.fundMetaLabel.Name = "fundMetaLabel";
        this.fundMetaLabel.Text = "Load a fund before running a scenario.";
        this.fundMetaLabel.TextAlign = ContentAlignment.TopLeft;

        // planParametersLabel
        this.planParametersLabel.Dock = DockStyle.Fill;
        this.planParametersLabel.Font = new Font("Consolas", 7.5F, FontStyle.Bold);
        this.planParametersLabel.ForeColor = Color.FromArgb(129, 147, 157);
        this.planParametersLabel.Name = "planParametersLabel";
        this.planParametersLabel.Text = "PLAN PARAMETERS";
        this.planParametersLabel.TextAlign = ContentAlignment.BottomLeft;

        // initialCapitalRow
        this.initialCapitalRow.BackColor = Color.FromArgb(0, 10, 18);
        this.initialCapitalRow.ColumnCount = 2;
        this.initialCapitalRow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 58F));
        this.initialCapitalRow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 42F));
        this.initialCapitalRow.Controls.Add(this.initialCapitalCopy, 0, 0);
        this.initialCapitalRow.Controls.Add(this.initialCapitalFrame, 1, 0);
        this.initialCapitalRow.Dock = DockStyle.Fill;
        this.initialCapitalRow.Margin = new Padding(0);
        this.initialCapitalRow.Name = "initialCapitalRow";
        this.initialCapitalRow.RowCount = 1;
        this.initialCapitalRow.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        this.initialCapitalCopy.BackColor = Color.FromArgb(0, 10, 18);
        this.initialCapitalCopy.ColumnCount = 1;
        this.initialCapitalCopy.Controls.Add(this.initialCapitalTitle, 0, 0);
        this.initialCapitalCopy.Controls.Add(this.initialCapitalDescription, 0, 1);
        this.initialCapitalCopy.Dock = DockStyle.Fill;
        this.initialCapitalCopy.Margin = new Padding(0);
        this.initialCapitalCopy.Name = "initialCapitalCopy";
        this.initialCapitalCopy.Padding = new Padding(0, 4, 8, 4);
        this.initialCapitalCopy.RowCount = 2;
        this.initialCapitalCopy.RowStyles.Add(new RowStyle(SizeType.Percent, 52F));
        this.initialCapitalCopy.RowStyles.Add(new RowStyle(SizeType.Percent, 48F));
        this.initialCapitalTitle.Dock = DockStyle.Fill;
        this.initialCapitalTitle.Font = new Font("Consolas", 8.75F, FontStyle.Bold);
        this.initialCapitalTitle.ForeColor = Color.FromArgb(238, 247, 251);
        this.initialCapitalTitle.Name = "initialCapitalTitle";
        this.initialCapitalTitle.Text = "Initial capital";
        this.initialCapitalTitle.TextAlign = ContentAlignment.BottomLeft;
        this.initialCapitalDescription.AutoEllipsis = true;
        this.initialCapitalDescription.Dock = DockStyle.Fill;
        this.initialCapitalDescription.Font = new Font("Segoe UI", 7.25F, FontStyle.Regular);
        this.initialCapitalDescription.ForeColor = Color.FromArgb(129, 147, 157);
        this.initialCapitalDescription.Name = "initialCapitalDescription";
        this.initialCapitalDescription.Text = "Capital invested at month zero";
        this.initialCapitalDescription.TextAlign = ContentAlignment.TopLeft;
        this.initialCapitalFrame.BorderColor = Color.FromArgb(38, 57, 70);
        this.initialCapitalFrame.Controls.Add(this.initialInvestment);
        this.initialCapitalFrame.CornerRadius = 7;
        this.initialCapitalFrame.Dock = DockStyle.Fill;
        this.initialCapitalFrame.FillColor = Color.FromArgb(0, 10, 18);
        this.initialCapitalFrame.Margin = new Padding(4, 8, 0, 8);
        this.initialCapitalFrame.Name = "initialCapitalFrame";
        this.initialCapitalFrame.Padding = new Padding(7, 4, 7, 3);
        this.initialInvestment.BackColor = Color.FromArgb(0, 10, 18);
        this.initialInvestment.BorderStyle = BorderStyle.None;
        this.initialInvestment.DecimalPlaces = 2;
        this.initialInvestment.Dock = DockStyle.Fill;
        this.initialInvestment.Font = new Font("Segoe UI", 10F, FontStyle.Regular);
        this.initialInvestment.ForeColor = Color.FromArgb(238, 247, 251);
        this.initialInvestment.Increment = new decimal(new int[] { 100, 0, 0, 0 });
        this.initialInvestment.Maximum = new decimal(new int[] { 100000000, 0, 0, 0 });
        this.initialInvestment.Minimum = new decimal(new int[] { 0, 0, 0, 0 });
        this.initialInvestment.Name = "initialInvestment";
        this.initialInvestment.ThousandsSeparator = true;
        this.initialInvestment.TextAlign = HorizontalAlignment.Right;
        this.initialInvestment.Value = new decimal(new int[] { 1800, 0, 0, 0 });

        // monthlyContributionRow
        this.monthlyContributionRow.BackColor = Color.FromArgb(0, 10, 18);
        this.monthlyContributionRow.ColumnCount = 2;
        this.monthlyContributionRow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 58F));
        this.monthlyContributionRow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 42F));
        this.monthlyContributionRow.Controls.Add(this.monthlyContributionCopy, 0, 0);
        this.monthlyContributionRow.Controls.Add(this.monthlyContributionFrame, 1, 0);
        this.monthlyContributionRow.Dock = DockStyle.Fill;
        this.monthlyContributionRow.Margin = new Padding(0);
        this.monthlyContributionRow.Name = "monthlyContributionRow";
        this.monthlyContributionRow.RowCount = 1;
        this.monthlyContributionRow.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        this.monthlyContributionCopy.BackColor = Color.FromArgb(0, 10, 18);
        this.monthlyContributionCopy.ColumnCount = 1;
        this.monthlyContributionCopy.Controls.Add(this.monthlyContributionTitle, 0, 0);
        this.monthlyContributionCopy.Controls.Add(this.monthlyContributionDescription, 0, 1);
        this.monthlyContributionCopy.Dock = DockStyle.Fill;
        this.monthlyContributionCopy.Margin = new Padding(0);
        this.monthlyContributionCopy.Name = "monthlyContributionCopy";
        this.monthlyContributionCopy.Padding = new Padding(0, 4, 8, 4);
        this.monthlyContributionCopy.RowCount = 2;
        this.monthlyContributionCopy.RowStyles.Add(new RowStyle(SizeType.Percent, 52F));
        this.monthlyContributionCopy.RowStyles.Add(new RowStyle(SizeType.Percent, 48F));
        this.monthlyContributionTitle.Dock = DockStyle.Fill;
        this.monthlyContributionTitle.Font = new Font("Consolas", 8.75F, FontStyle.Bold);
        this.monthlyContributionTitle.ForeColor = Color.FromArgb(238, 247, 251);
        this.monthlyContributionTitle.Name = "monthlyContributionTitle";
        this.monthlyContributionTitle.Text = "Monthly contribution";
        this.monthlyContributionTitle.TextAlign = ContentAlignment.BottomLeft;
        this.monthlyContributionDescription.AutoEllipsis = true;
        this.monthlyContributionDescription.Dock = DockStyle.Fill;
        this.monthlyContributionDescription.Font = new Font("Segoe UI", 7.25F, FontStyle.Regular);
        this.monthlyContributionDescription.ForeColor = Color.FromArgb(129, 147, 157);
        this.monthlyContributionDescription.Name = "monthlyContributionDescription";
        this.monthlyContributionDescription.Text = "Contribution at each month end";
        this.monthlyContributionDescription.TextAlign = ContentAlignment.TopLeft;
        this.monthlyContributionFrame.BorderColor = Color.FromArgb(38, 57, 70);
        this.monthlyContributionFrame.Controls.Add(this.monthlyContribution);
        this.monthlyContributionFrame.CornerRadius = 7;
        this.monthlyContributionFrame.Dock = DockStyle.Fill;
        this.monthlyContributionFrame.FillColor = Color.FromArgb(0, 10, 18);
        this.monthlyContributionFrame.Margin = new Padding(4, 8, 0, 8);
        this.monthlyContributionFrame.Name = "monthlyContributionFrame";
        this.monthlyContributionFrame.Padding = new Padding(7, 4, 7, 3);
        this.monthlyContribution.BackColor = Color.FromArgb(0, 10, 18);
        this.monthlyContribution.BorderStyle = BorderStyle.None;
        this.monthlyContribution.DecimalPlaces = 2;
        this.monthlyContribution.Dock = DockStyle.Fill;
        this.monthlyContribution.Font = new Font("Segoe UI", 10F, FontStyle.Regular);
        this.monthlyContribution.ForeColor = Color.FromArgb(238, 247, 251);
        this.monthlyContribution.Increment = new decimal(new int[] { 25, 0, 0, 0 });
        this.monthlyContribution.Maximum = new decimal(new int[] { 100000000, 0, 0, 0 });
        this.monthlyContribution.Minimum = new decimal(new int[] { 0, 0, 0, 0 });
        this.monthlyContribution.Name = "monthlyContribution";
        this.monthlyContribution.ThousandsSeparator = true;
        this.monthlyContribution.TextAlign = HorizontalAlignment.Right;
        this.monthlyContribution.Value = new decimal(new int[] { 100, 0, 0, 0 });

        // horizonYearsRow
        this.horizonYearsRow.BackColor = Color.FromArgb(0, 10, 18);
        this.horizonYearsRow.ColumnCount = 2;
        this.horizonYearsRow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 58F));
        this.horizonYearsRow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 42F));
        this.horizonYearsRow.Controls.Add(this.horizonYearsCopy, 0, 0);
        this.horizonYearsRow.Controls.Add(this.horizonYearsFrame, 1, 0);
        this.horizonYearsRow.Dock = DockStyle.Fill;
        this.horizonYearsRow.Margin = new Padding(0);
        this.horizonYearsRow.Name = "horizonYearsRow";
        this.horizonYearsRow.RowCount = 1;
        this.horizonYearsRow.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        this.horizonYearsCopy.BackColor = Color.FromArgb(0, 10, 18);
        this.horizonYearsCopy.ColumnCount = 1;
        this.horizonYearsCopy.Controls.Add(this.horizonYearsTitle, 0, 0);
        this.horizonYearsCopy.Controls.Add(this.horizonYearsDescription, 0, 1);
        this.horizonYearsCopy.Dock = DockStyle.Fill;
        this.horizonYearsCopy.Margin = new Padding(0);
        this.horizonYearsCopy.Name = "horizonYearsCopy";
        this.horizonYearsCopy.Padding = new Padding(0, 4, 8, 4);
        this.horizonYearsCopy.RowCount = 2;
        this.horizonYearsCopy.RowStyles.Add(new RowStyle(SizeType.Percent, 52F));
        this.horizonYearsCopy.RowStyles.Add(new RowStyle(SizeType.Percent, 48F));
        this.horizonYearsTitle.Dock = DockStyle.Fill;
        this.horizonYearsTitle.Font = new Font("Consolas", 8.75F, FontStyle.Bold);
        this.horizonYearsTitle.ForeColor = Color.FromArgb(238, 247, 251);
        this.horizonYearsTitle.Name = "horizonYearsTitle";
        this.horizonYearsTitle.Text = "Investment horizon";
        this.horizonYearsTitle.TextAlign = ContentAlignment.BottomLeft;
        this.horizonYearsDescription.AutoEllipsis = true;
        this.horizonYearsDescription.Dock = DockStyle.Fill;
        this.horizonYearsDescription.Font = new Font("Segoe UI", 7.25F, FontStyle.Regular);
        this.horizonYearsDescription.ForeColor = Color.FromArgb(129, 147, 157);
        this.horizonYearsDescription.Name = "horizonYearsDescription";
        this.horizonYearsDescription.Text = "Years projected from the latest NAV";
        this.horizonYearsDescription.TextAlign = ContentAlignment.TopLeft;
        this.horizonYearsFrame.BorderColor = Color.FromArgb(38, 57, 70);
        this.horizonYearsFrame.Controls.Add(this.horizonYears);
        this.horizonYearsFrame.CornerRadius = 7;
        this.horizonYearsFrame.Dock = DockStyle.Fill;
        this.horizonYearsFrame.FillColor = Color.FromArgb(0, 10, 18);
        this.horizonYearsFrame.Margin = new Padding(4, 8, 0, 8);
        this.horizonYearsFrame.Name = "horizonYearsFrame";
        this.horizonYearsFrame.Padding = new Padding(7, 4, 7, 3);
        this.horizonYears.BackColor = Color.FromArgb(0, 10, 18);
        this.horizonYears.BorderStyle = BorderStyle.None;
        this.horizonYears.DecimalPlaces = 0;
        this.horizonYears.Dock = DockStyle.Fill;
        this.horizonYears.Font = new Font("Segoe UI", 10F, FontStyle.Regular);
        this.horizonYears.ForeColor = Color.FromArgb(238, 247, 251);
        this.horizonYears.Increment = new decimal(new int[] { 1, 0, 0, 0 });
        this.horizonYears.Maximum = new decimal(new int[] { 50, 0, 0, 0 });
        this.horizonYears.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
        this.horizonYears.Name = "horizonYears";
        this.horizonYears.ThousandsSeparator = true;
        this.horizonYears.TextAlign = HorizontalAlignment.Right;
        this.horizonYears.Value = new decimal(new int[] { 10, 0, 0, 0 });

        // pathCountRow
        this.pathCountRow.BackColor = Color.FromArgb(0, 10, 18);
        this.pathCountRow.ColumnCount = 2;
        this.pathCountRow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 58F));
        this.pathCountRow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 42F));
        this.pathCountRow.Controls.Add(this.pathCountCopy, 0, 0);
        this.pathCountRow.Controls.Add(this.pathCountFrame, 1, 0);
        this.pathCountRow.Dock = DockStyle.Fill;
        this.pathCountRow.Margin = new Padding(0);
        this.pathCountRow.Name = "pathCountRow";
        this.pathCountRow.RowCount = 1;
        this.pathCountRow.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        this.pathCountCopy.BackColor = Color.FromArgb(0, 10, 18);
        this.pathCountCopy.ColumnCount = 1;
        this.pathCountCopy.Controls.Add(this.pathCountTitle, 0, 0);
        this.pathCountCopy.Controls.Add(this.pathCountDescription, 0, 1);
        this.pathCountCopy.Dock = DockStyle.Fill;
        this.pathCountCopy.Margin = new Padding(0);
        this.pathCountCopy.Name = "pathCountCopy";
        this.pathCountCopy.Padding = new Padding(0, 4, 8, 4);
        this.pathCountCopy.RowCount = 2;
        this.pathCountCopy.RowStyles.Add(new RowStyle(SizeType.Percent, 52F));
        this.pathCountCopy.RowStyles.Add(new RowStyle(SizeType.Percent, 48F));
        this.pathCountTitle.Dock = DockStyle.Fill;
        this.pathCountTitle.Font = new Font("Consolas", 8.75F, FontStyle.Bold);
        this.pathCountTitle.ForeColor = Color.FromArgb(238, 247, 251);
        this.pathCountTitle.Name = "pathCountTitle";
        this.pathCountTitle.Text = "Monte Carlo paths";
        this.pathCountTitle.TextAlign = ContentAlignment.BottomLeft;
        this.pathCountDescription.AutoEllipsis = true;
        this.pathCountDescription.Dock = DockStyle.Fill;
        this.pathCountDescription.Font = new Font("Segoe UI", 7.25F, FontStyle.Regular);
        this.pathCountDescription.ForeColor = Color.FromArgb(129, 147, 157);
        this.pathCountDescription.Name = "pathCountDescription";
        this.pathCountDescription.Text = "Independent simulated trajectories";
        this.pathCountDescription.TextAlign = ContentAlignment.TopLeft;
        this.pathCountFrame.BorderColor = Color.FromArgb(38, 57, 70);
        this.pathCountFrame.Controls.Add(this.pathCount);
        this.pathCountFrame.CornerRadius = 7;
        this.pathCountFrame.Dock = DockStyle.Fill;
        this.pathCountFrame.FillColor = Color.FromArgb(0, 10, 18);
        this.pathCountFrame.Margin = new Padding(4, 8, 0, 8);
        this.pathCountFrame.Name = "pathCountFrame";
        this.pathCountFrame.Padding = new Padding(7, 4, 7, 3);
        this.pathCount.BackColor = Color.FromArgb(0, 10, 18);
        this.pathCount.BorderStyle = BorderStyle.None;
        this.pathCount.DecimalPlaces = 0;
        this.pathCount.Dock = DockStyle.Fill;
        this.pathCount.Font = new Font("Segoe UI", 10F, FontStyle.Regular);
        this.pathCount.ForeColor = Color.FromArgb(238, 247, 251);
        this.pathCount.Increment = new decimal(new int[] { 500, 0, 0, 0 });
        this.pathCount.Maximum = new decimal(new int[] { 100000, 0, 0, 0 });
        this.pathCount.Minimum = new decimal(new int[] { 100, 0, 0, 0 });
        this.pathCount.Name = "pathCount";
        this.pathCount.ThousandsSeparator = true;
        this.pathCount.TextAlign = HorizontalAlignment.Right;
        this.pathCount.Value = new decimal(new int[] { 5000, 0, 0, 0 });

        // runButton
        this.runButton.Dock = DockStyle.Fill;
        this.runButton.Kind = AletheiaButtonKind.Primary;
        this.runButton.Margin = new Padding(0, 5, 0, 5);
        this.runButton.Name = "runButton";
        this.runButton.Text = "Run baseline scenario";

        // assumptionCard
        this.assumptionCard.BorderColor = Color.FromArgb(77, 145, 168);
        this.assumptionCard.Controls.Add(this.assumptionLayout);
        this.assumptionCard.CornerRadius = 8;
        this.assumptionCard.Dock = DockStyle.Fill;
        this.assumptionCard.FillColor = Color.FromArgb(20, 56, 74);
        this.assumptionCard.Margin = new Padding(0, 8, 0, 8);
        this.assumptionCard.Name = "assumptionCard";
        this.assumptionCard.Padding = new Padding(12, 9, 12, 8);
        this.assumptionLayout.BackColor = Color.FromArgb(20, 56, 74);
        this.assumptionLayout.ColumnCount = 1;
        this.assumptionLayout.Controls.Add(this.assumptionTitleLabel, 0, 0);
        this.assumptionLayout.Controls.Add(this.assumptionDescriptionLabel, 0, 1);
        this.assumptionLayout.Dock = DockStyle.Fill;
        this.assumptionLayout.Margin = new Padding(0);
        this.assumptionLayout.Name = "assumptionLayout";
        this.assumptionLayout.RowCount = 2;
        this.assumptionLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 23F));
        this.assumptionLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        this.assumptionTitleLabel.Dock = DockStyle.Fill;
        this.assumptionTitleLabel.Font = new Font("Consolas", 7.5F, FontStyle.Bold);
        this.assumptionTitleLabel.ForeColor = Color.FromArgb(96, 192, 224);
        this.assumptionTitleLabel.Name = "assumptionTitleLabel";
        this.assumptionTitleLabel.Text = "BASELINE, NOT A FORECAST";
        this.assumptionTitleLabel.TextAlign = ContentAlignment.MiddleLeft;
        this.assumptionDescriptionLabel.Dock = DockStyle.Fill;
        this.assumptionDescriptionLabel.Font = new Font("Segoe UI", 8F, FontStyle.Regular);
        this.assumptionDescriptionLabel.ForeColor = Color.FromArgb(186, 200, 209);
        this.assumptionDescriptionLabel.Name = "assumptionDescriptionLabel";
        this.assumptionDescriptionLabel.Text = "IID Gaussian log returns with monthly moment scaling and end-of-month contributions. Fees, taxes and inflation are excluded.";
        this.assumptionDescriptionLabel.TextAlign = ContentAlignment.TopLeft;

        // stateLabel
        this.stateLabel.AutoEllipsis = true;
        this.stateLabel.Dock = DockStyle.Fill;
        this.stateLabel.Font = new Font("Segoe UI", 8.5F, FontStyle.Regular);
        this.stateLabel.ForeColor = Color.FromArgb(186, 200, 209);
        this.stateLabel.Name = "stateLabel";
        this.stateLabel.Text = "Load a fund to begin.";
        this.stateLabel.TextAlign = ContentAlignment.BottomLeft;

        // resultsLayout
        this.resultsLayout.BackColor = Color.FromArgb(0, 7, 12);
        this.resultsLayout.ColumnCount = 1;
        this.resultsLayout.Controls.Add(this.metrics, 0, 0);
        this.resultsLayout.Controls.Add(this.trajectoryChart, 0, 1);
        this.resultsLayout.Controls.Add(this.detailsCard, 0, 2);
        this.resultsLayout.Dock = DockStyle.Fill;
        this.resultsLayout.Margin = new Padding(0);
        this.resultsLayout.Name = "resultsLayout";
        this.resultsLayout.Padding = new Padding(0);
        this.resultsLayout.RowCount = 3;
        this.resultsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 96F));
        this.resultsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 63F));
        this.resultsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 37F));
        this.metrics.Dock = DockStyle.Fill;
        this.metrics.Margin = new Padding(6);
        this.metrics.Name = "metrics";
        this.trajectoryChart.Dock = DockStyle.Fill;
        this.trajectoryChart.Margin = new Padding(6);
        this.trajectoryChart.Name = "trajectoryChart";
        this.detailsCard.CardSubtitle = "Inputs, return scaling, distribution and methodology";
        this.detailsCard.CardTitle = "Scenario diagnostics";
        this.detailsCard.ShowCount = false;
        this.detailsCard.Dock = DockStyle.Fill;
        this.detailsCard.Margin = new Padding(6);
        this.detailsCard.Name = "detailsCard";

        // SimulationPage
        this.AutoScaleDimensions = new SizeF(7F, 15F);
        this.AutoScaleMode = AutoScaleMode.Font;
        this.BackColor = Color.FromArgb(0, 7, 12);
        this.Controls.Add(this.rootLayout);
        this.Dock = DockStyle.Fill;
        this.Name = "SimulationPage";
        this.Size = new Size(1200, 760);
        ((System.ComponentModel.ISupportInitialize)this.initialInvestment).EndInit();
        ((System.ComponentModel.ISupportInitialize)this.monthlyContribution).EndInit();
        ((System.ComponentModel.ISupportInitialize)this.horizonYears).EndInit();
        ((System.ComponentModel.ISupportInitialize)this.pathCount).EndInit();
        this.resultsLayout.ResumeLayout(false);
        this.assumptionLayout.ResumeLayout(false);
        this.assumptionCard.ResumeLayout(false);
        this.pathCountFrame.ResumeLayout(false);
        this.pathCountDescription.ResumeLayout(false);
        this.pathCountTitle.ResumeLayout(false);
        this.pathCountCopy.ResumeLayout(false);
        this.pathCountRow.ResumeLayout(false);
        this.horizonYearsFrame.ResumeLayout(false);
        this.horizonYearsDescription.ResumeLayout(false);
        this.horizonYearsTitle.ResumeLayout(false);
        this.horizonYearsCopy.ResumeLayout(false);
        this.horizonYearsRow.ResumeLayout(false);
        this.monthlyContributionFrame.ResumeLayout(false);
        this.monthlyContributionDescription.ResumeLayout(false);
        this.monthlyContributionTitle.ResumeLayout(false);
        this.monthlyContributionCopy.ResumeLayout(false);
        this.monthlyContributionRow.ResumeLayout(false);
        this.initialCapitalFrame.ResumeLayout(false);
        this.initialCapitalDescription.ResumeLayout(false);
        this.initialCapitalTitle.ResumeLayout(false);
        this.initialCapitalCopy.ResumeLayout(false);
        this.initialCapitalRow.ResumeLayout(false);
        this.datasetLayout.ResumeLayout(false);
        this.datasetCard.ResumeLayout(false);
        this.configurationHeader.ResumeLayout(false);
        this.configurationLayout.ResumeLayout(false);
        this.configurationCard.ResumeLayout(false);
        this.rootLayout.ResumeLayout(false);
        this.ResumeLayout(false);
    }
}
